name: Example workflow using Snyk
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: snyk/actions/setup@master
        - uses: actions/setup-node@v3
        - name: Snyk monitor
          run: snyk code test --sarif
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}